version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
permissions:
  - object: /
    pattern: 775
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
  AfterInstall:
    - location: /stop.sh #  Stop current running server
      timeout: 60
      runas: root
  ApplicationStart:
    - location: /deploy.sh
      timeout: 60
      runas: root