version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
permissions:
  - object: /
    pattern "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: script/stop.sh #  Stop current running server
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: script/deploy.sh
      timeout: 60
      runas: ubuntu