# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, develop,chore_ec2_deploy ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set properties
      env:
        PROPS: ${{ secrets.PROPERTIES }}
      run: |
        mkdir ./src/main/resources
        touch ./src/main/resources/application.properties
        echo "$PROPS" > ./src/main/resources/application.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #build
    - name: Build with Gradle
      run: ./gradlew clean build
    # Make file directory
    - name: Make Directory to deliver files
      run: mkdir deploy
    # JAR file copy from build/libs
    - name: Copy Jar
      run: cp ./build/libs/*SNAPSHOT.jar ./deploy/
    # transfer file as .zip
    - name: Make zip file
      run: zip -r -qq -j ./balance-vote-server.zip ./deploy
    # copy to S3 bucket
    - name: Deliver to AWS S3
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./balance-vote-server.zip s3://balance-vote-bucket/
      #deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name BalanceVoteDeployApp \
        --deployment-group-name BalanceVote \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=balance-vote-bucket,bundleType=zip,key=balance-vote-server.zip \
        --region ap-northeast-2